apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-demo-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-demo-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        - name: sidecar
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
